drone_name: "iris"
num_rotors: 4
rotor_0:
  link_name: "iris/rotor_0"
  direction: "ccw"
  max_velocity: 838.
  motor_constant: 8.54858e-6
  moment_constant: 0.016
rotor_1:
  link_name: "iris/rotor_1"
  direction: "ccw"
  max_velocity: 838.
  motor_constant: 8.54858e-6
  moment_constant: 0.016
rotor_2:
  link_name: "iris/rotor_2"
  direction: "cw"
  max_velocity: 838.
  motor_constant: 8.54858e-6
  moment_constant: 0.016
rotor_3:
  link_name: "iris/rotor_3"
  direction: "cw"
  max_velocity: 838.
  motor_constant: 8.54858e-6
  moment_constant: 0.016
